base: 'https://tsv-ladbergen.ddev.site/'
languages:
    - title: German
      enabled: true
      languageId: 0
      base: /
      locale: de_DE
      navigationTitle: German
      flag: de
      hreflang: ''
      websiteTitle: ''
      fallbackType: strict
      fallbacks: ''
rootPageId: 1
websiteTitle: ''
